<?php

namespace Pixel\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    
  public function getPosts($nombreParPage, $page)
  {
    if ((int) $page < 1) {
      throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
    }

    $query = $this->createQueryBuilder('a')
                  ->orderBy('a.id', 'DESC')
                  ->getQuery();

    $query->setFirstResult(($page-1) * $nombreParPage)
          ->setMaxResults($nombreParPage);

    return new Paginator($query);
  }
}
